#开发环境
server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&type=MyISAM
    username: root
    password: root.1217
    hikari:
      #池中最大链接数
      maximum-pool-size: 50
      #池中链接最长生命周期
      max-lifetime: 120000
      #连接允许在池中闲置的最长时间
      idle-timeout: 600000
      #等待来自池的连接的最大毫秒数
      connection-timeout: 30000
      #池中最小空闲链接数
      minimum-idle: 10

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    open-in-view: false #懒加载时使用，建议false


zj:
  hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    packages-to-scan: com.zj
    current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
